In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.animation as animation
import matplotlib as mpl
from timeit import default_timer as timer
from tqdm import tqdm

In [2]:
def add_offspring(model, lx, ly, adda):    
    zero_loc = np.where(model==0)

    k = np.shape(zero_loc)[1]

    add_model = np.zeros((lx,ly))
    counta = 0

    while counta < adda:
        for i in range(0,k):
            add_model[zero_loc[0][i], zero_loc[1][i]] = -1
            counta = counta + 1

            if counta == adda:
                break

    model = model + add_model
    return model

In [7]:
np.random.poisson(1)

3

In [8]:
#Number of experiments
N = 100

success = 0
fail = 0

#Number of iteration
T = 1000

#A's prob. of death
Pd = 0.3
#A's prob. of live and produce ONE offspring
Ps = 0.6

#Dimension of lattice
lx = 50
ly = 50

np.random.seed(97)

for nn in tqdm(range (0,N)): 
    if nn%5 == 0:
        print('Experiment number =' + str(nn))

        print('Number of success = ' + str(success))
        print('Number of failure = ' + str(fail))

    model = np.zeros((lx,ly))
    
    #Race A: -1, Vacant spot: 0
    model[0,0] = -1

    for k in range(0,T):
    
        test = model.flatten().tolist()
        if -1 not in test:
            print('Fixation has failed at iteration number ' + str(k))
            fail = fail + 1
            break
            
        adda = 0

        prob_matrix = np.random.random((lx,ly))

        A_loc = np.where(model == -1)

        n_A = np.shape(A_loc)[1]


        for i in range(0, n_A):
            #A dies
            if prob_matrix[A_loc[0][i], A_loc[1][i]] <= Pd:

                model[A_loc[0][i], A_loc[1][i]] = 0

            #Live and prosperous
            elif prob_matrix[A_loc[0][i], A_loc[1][i]] > Pd and\
                prob_matrix[A_loc[0][i], A_loc[1][i]] <= (Pd + Ps):

                poisson_ = np.random.poisson(1)
                adda = adda + poisson_

        #Do another loop to add the offsprings

        n_vacant = lx*ly - np.count_nonzero(model)
        toadd = adda
        
        if toadd <= n_vacant:
            model = add_offspring(model, lx, ly, adda)

        else:
            model = np.ones((lx,ly)) * -1

        if k == T-1:
            success = success + 1


  0%|          | 0/100 [00:00<?, ?it/s]

Experiment number =0
Number of success = 0
Number of failure = 0


  1%|          | 1/100 [00:16<27:22, 16.60s/it]

Fixation has failed at iteration number 2


  3%|▎         | 3/100 [00:32<16:37, 10.28s/it]

Fixation has failed at iteration number 2


  5%|▌         | 5/100 [00:49<14:32,  9.18s/it]

Experiment number =5
Number of success = 3
Number of failure = 2
Fixation has failed at iteration number 1


  9%|▉         | 9/100 [01:18<11:43,  7.74s/it]

Fixation has failed at iteration number 1
Experiment number =10
Number of success = 6
Number of failure = 4


 12%|█▏        | 12/100 [01:30<08:34,  5.85s/it]

Fixation has failed at iteration number 9
Fixation has failed at iteration number 1
Fixation has failed at iteration number 4
Experiment number =15
Number of success = 8
Number of failure = 7


 17%|█▋        | 17/100 [01:42<05:15,  3.80s/it]

Fixation has failed at iteration number 2
Fixation has failed at iteration number 2
Fixation has failed at iteration number 1
Experiment number =20
Number of success = 10
Number of failure = 10
Fixation has failed at iteration number 2


 24%|██▍       | 24/100 [01:59<04:16,  3.38s/it]

Fixation has failed at iteration number 1
Experiment number =25
Number of success = 13
Number of failure = 12
Fixation has failed at iteration number 1


 27%|██▋       | 27/100 [02:05<03:25,  2.82s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 5
Fixation has failed at iteration number 1
Experiment number =30
Number of success = 14
Number of failure = 16


 31%|███       | 31/100 [02:11<02:33,  2.23s/it]

Fixation has failed at iteration number 7
Fixation has failed at iteration number 2
Fixation has failed at iteration number 1
Fixation has failed at iteration number 1
Experiment number =35
Number of success = 15
Number of failure = 20
Fixation has failed at iteration number 2


 40%|████      | 40/100 [02:34<03:01,  3.02s/it]

Experiment number =40
Number of success = 19
Number of failure = 21


 43%|████▎     | 43/100 [02:52<04:08,  4.37s/it]

Fixation has failed at iteration number 1


 45%|████▌     | 45/100 [02:57<03:27,  3.77s/it]

Experiment number =45
Number of success = 23
Number of failure = 22
Fixation has failed at iteration number 1
Fixation has failed at iteration number 3


 48%|████▊     | 48/100 [03:04<02:37,  3.03s/it]

Fixation has failed at iteration number 2


 50%|█████     | 50/100 [03:10<02:32,  3.05s/it]

Experiment number =50
Number of success = 25
Number of failure = 25
Fixation has failed at iteration number 4
Fixation has failed at iteration number 1


 53%|█████▎    | 53/100 [03:16<02:02,  2.62s/it]

Fixation has failed at iteration number 3
Fixation has failed at iteration number 1
Experiment number =55
Number of success = 26
Number of failure = 29
Fixation has failed at iteration number 1


 57%|█████▋    | 57/100 [03:22<01:31,  2.13s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 1
Fixation has failed at iteration number 1
Experiment number =60
Number of success = 27
Number of failure = 33
Fixation has failed at iteration number 2
Fixation has failed at iteration number 4


 64%|██████▍   | 64/100 [03:35<01:15,  2.10s/it]

Fixation has failed at iteration number 2
Experiment number =65
Number of success = 29
Number of failure = 36
Fixation has failed at iteration number 3
Fixation has failed at iteration number 4


 68%|██████▊   | 68/100 [03:40<00:59,  1.87s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 8
Experiment number =70
Number of success = 30
Number of failure = 40


 71%|███████   | 71/100 [03:46<00:53,  1.86s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 3
Fixation has failed at iteration number 2
Fixation has failed at iteration number 1
Experiment number =75
Number of success = 31
Number of failure = 44
Fixation has failed at iteration number 1
Fixation has failed at iteration number 3
Fixation has failed at iteration number 5


 80%|████████  | 80/100 [04:03<00:40,  2.02s/it]

Experiment number =80
Number of success = 33
Number of failure = 47


 82%|████████▏ | 82/100 [04:17<00:54,  3.03s/it]

Fixation has failed at iteration number 1


 85%|████████▌ | 85/100 [04:30<00:54,  3.65s/it]

Experiment number =85
Number of success = 37
Number of failure = 48


 86%|████████▌ | 86/100 [04:36<00:57,  4.08s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 1
Fixation has failed at iteration number 3
Fixation has failed at iteration number 1
Experiment number =90
Number of success = 38
Number of failure = 52
Fixation has failed at iteration number 1


 92%|█████████▏| 92/100 [04:41<00:17,  2.15s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 2


 95%|█████████▌| 95/100 [04:47<00:10,  2.11s/it]

Experiment number =95
Number of success = 40
Number of failure = 55
Fixation has failed at iteration number 3
Fixation has failed at iteration number 1
Fixation has failed at iteration number 1


100%|██████████| 100/100 [04:53<00:00,  2.94s/it]

Fixation has failed at iteration number 2


In [9]:
success

41

In [10]:
fail

59

In [38]:
model = np.zeros((3, 3))

In [39]:
model

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
model[0,0] = -1
model[1,1] = -1

In [41]:
model

array([[-1.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  0.]])

In [42]:
A_loc = np.where(model == -1)
A_loc

(array([0, 1], dtype=int64), array([0, 1], dtype=int64))

In [43]:
model = add_offspring(model, 3, 3, 1)

In [44]:
model

array([[-1., -1.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  0.]])

In [45]:
aa = np.shape(A_loc)[1]
for i in range(0,aa):
    model[A_loc[0][i], A_loc[1][i]] = 0

In [46]:
model

array([[ 0., -1.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [47]:
A_loc = np.where(model == -1)
A_loc

(array([0], dtype=int64), array([1], dtype=int64))

In [48]:
model = add_offspring(model, 3, 3, 2)
model

array([[-1., -1., -1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [49]:
aa = np.shape(A_loc)[1]
for i in range(0,aa):
    model[A_loc[0][i], A_loc[1][i]] = 0

In [50]:
model

array([[-1.,  0., -1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [51]:
#Number of experiments
N = 100

success = 0
fail = 0

#Number of iteration
T = 1000

#Dimension of lattice
lx = 50
ly = 50

for nn in tqdm(range (0,N)): 
    if nn%5 == 0:
        print('Experiment number =' + str(nn))

        print('Number of success = ' + str(success))
        print('Number of failure = ' + str(fail))

    model = np.zeros((lx,ly))
    
    #Race A: -1, Vacant spot: 0
    model[0,0] = -1

    for k in range(0,T):
    
        test = model.flatten().tolist()
        if -1 not in test:
            print('Fixation has failed at iteration number ' + str(k))
            fail = fail + 1
            break
            
        adda = 0
        
        #find where A is
        A_loc = np.where(model == -1)
        n_A = np.shape(A_loc)[1]

        for i in range(0, n_A):
            #let A reproduce offpsring following poisson
            poisson_ = np.random.poisson(2)
            adda = adda + poisson_
        
        #kill original A
            model[A_loc[0][i], A_loc[1][i]] = 0
        
        #Do another loop to add the offsprings

        n_vacant = lx*ly - np.count_nonzero(model)
        toadd = adda
        
        if toadd <= n_vacant:
            model = add_offspring(model, lx, ly, adda)

        else:
            model = np.ones((lx,ly)) * -1

        if k == T-1:
            success = success + 1


  0%|          | 0/100 [00:00<?, ?it/s]

Experiment number =0
Number of success = 0
Number of failure = 0


  3%|▎         | 3/100 [00:13<07:20,  4.54s/it]

Fixation has failed at iteration number 1


  5%|▌         | 5/100 [00:18<05:10,  3.27s/it]

Experiment number =5
Number of success = 4
Number of failure = 1
Fixation has failed at iteration number 1


 10%|█         | 10/100 [00:36<05:50,  3.89s/it]

Experiment number =10
Number of success = 8
Number of failure = 2


 15%|█▌        | 15/100 [01:00<06:19,  4.47s/it]

Experiment number =15
Number of success = 13
Number of failure = 2


 16%|█▌        | 16/100 [01:04<06:16,  4.48s/it]

Fixation has failed at iteration number 1


 18%|█▊        | 18/100 [01:09<04:45,  3.48s/it]

Fixation has failed at iteration number 1


 20%|██        | 20/100 [01:13<03:57,  2.97s/it]

Experiment number =20
Number of success = 16
Number of failure = 4


 23%|██▎       | 23/100 [01:26<04:51,  3.78s/it]

Fixation has failed at iteration number 2
Fixation has failed at iteration number 1
Experiment number =25
Number of success = 19
Number of failure = 6


 29%|██▉       | 29/100 [01:45<04:22,  3.70s/it]

Fixation has failed at iteration number 1
Experiment number =30
Number of success = 23
Number of failure = 7


 34%|███▍      | 34/100 [02:04<04:27,  4.05s/it]

Fixation has failed at iteration number 1
Experiment number =35
Number of success = 27
Number of failure = 8


 40%|████      | 40/100 [02:27<04:10,  4.18s/it]

Experiment number =40
Number of success = 32
Number of failure = 8
Fixation has failed at iteration number 1


 45%|████▌     | 45/100 [02:45<03:40,  4.00s/it]

Experiment number =45
Number of success = 36
Number of failure = 9


 50%|█████     | 50/100 [03:08<03:40,  4.40s/it]

Experiment number =50
Number of success = 41
Number of failure = 9


 51%|█████     | 51/100 [03:12<03:38,  4.47s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 1


 54%|█████▍    | 54/100 [03:17<02:08,  2.79s/it]

Fixation has failed at iteration number 7
Experiment number =55
Number of success = 43
Number of failure = 12


 59%|█████▉    | 59/100 [03:35<02:28,  3.63s/it]

Fixation has failed at iteration number 1
Experiment number =60
Number of success = 47
Number of failure = 13
Fixation has failed at iteration number 2


 65%|██████▌   | 65/100 [03:53<02:06,  3.62s/it]

Experiment number =65
Number of success = 51
Number of failure = 14


 68%|██████▊   | 68/100 [04:07<02:16,  4.26s/it]

Fixation has failed at iteration number 4
Fixation has failed at iteration number 2
Experiment number =70
Number of success = 54
Number of failure = 16


 71%|███████   | 71/100 [04:12<01:20,  2.77s/it]

Fixation has failed at iteration number 1


 75%|███████▌  | 75/100 [04:26<01:25,  3.41s/it]

Experiment number =75
Number of success = 58
Number of failure = 17


 80%|████████  | 80/100 [04:48<01:24,  4.25s/it]

Experiment number =80
Number of success = 63
Number of failure = 17


 82%|████████▏ | 82/100 [04:57<01:19,  4.40s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 3


 85%|████████▌ | 85/100 [05:02<00:42,  2.81s/it]

Experiment number =85
Number of success = 66
Number of failure = 19


 87%|████████▋ | 87/100 [05:12<00:48,  3.75s/it]

Fixation has failed at iteration number 1
Fixation has failed at iteration number 2


 90%|█████████ | 90/100 [05:18<00:28,  2.82s/it]

Experiment number =90
Number of success = 69
Number of failure = 21
Fixation has failed at iteration number 1
Fixation has failed at iteration number 1


 95%|█████████▌| 95/100 [05:33<00:15,  3.16s/it]

Experiment number =95
Number of success = 72
Number of failure = 23


 98%|█████████▊| 98/100 [05:47<00:07,  3.97s/it]

Fixation has failed at iteration number 1


100%|██████████| 100/100 [05:52<00:00,  3.52s/it]


In [52]:
success

76

In [53]:
fail

24