In [1]:
import numpy as np
import matplotlib.pyplot as plt
import statistics as st

Generate state: type 1 variant, type -1 variant. Start with N fixed 

In [2]:
def state_generator(L):
    #generate matrix with size LxL based on probabilities
    return np.random.choice([-1, 1], (L,L), p = [0.1, 0.9])

In [3]:
state = state_generator(3)
state

array([[ 1,  1,  1],
       [ 1,  1,  1],
       [-1,  1,  1]])

In [4]:
#count number of N and n, n is type 1 variant
lx, ly = state.shape
N = lx*ly
n = (state.flatten()==-1).sum()
# type1 = (state.flatten()==-1).sum()
# type2 = (state.flatten()==1).sum()

#probability of type 1,2 variant reproducing: with type 1 variant as more fit
r = 1.05
rep_p1 = r*n/(r*n + N-n)
rep_p2 = (N-n)/(r*n + N-n)
#probability of elimination for type 1,2 variant
die_p1 = n/N
die_p2 = (N-n)/N

flattened_state = state.flatten()
#choose 1 element from the state to reproduce
chosen_index_rep = np.random.randint(0,lx**2) 
original_element_rep = flattened_state[chosen_index_rep]

#choose 1 element from the state to die
chosen_index_die = np.random.randint(0,lx**2)
original_element_die = flattened_state[chosen_index_die]

#apply condition to determine how many new elements are after 1 time step of reproduction
rep_type1 = 0
rep_type2 = 0
#if chosen element to reproduce is type1 variant
if original_element_rep == n:
    print('type1')
    rep_type1 = np.random.binomial(N, rep_p1)
#else type 2 variant reproduces
else:
    rep_type2 = np.random.binomial(N, rep_p2)

#apply condition to determine how many died
die_type1 = 0
die_type2 = 0
if original_element_die == n:
    print('type1')
    die_type1 = np.random.binomial(N, die_p1)
else:
    die_type2 = np.random.binomial(N, die_p2)

type1
type1


In [11]:
new_n = n + rep_type1 - die_type1
new_N = N - new_n

In [12]:
new_n

3

In [13]:
new_N

6

In [14]:
#new_state
list_ = [-1]*new_n + [1]*new_N
new_state = np.array(list_).reshape(lx,ly)
new_state

array([[-1, -1, -1],
       [ 1,  1,  1],
       [ 1,  1,  1]])

after an iteration is finished, increase N by padding zeros

In [16]:
new_shape = (4,4)
shape_diff = np.array(new_shape) - np.array(new_state.shape)

In [18]:
#this becomes new state after next iteration
np.lib.pad(new_state, ((0,shape_diff[0]),(0,shape_diff[1])), 
                              'constant', constant_values=(0))

array([[-1, -1, -1,  0],
       [ 1,  1,  1,  0],
       [ 1,  1,  1,  0],
       [ 0,  0,  0,  0]])

In [19]:
#then we calculate N, n, and probabilities again given this matrix - but note how to handle the zeros.

#### end

In [4]:
new_state = []
lx, ly = state.shape
for i_pair, s in np.ndenumerate(state):
    #get the 4 neighbors for each s using periodic boundary conditions
    nb1 = state[(i_pair[0], (i_pair[1]+1)%ly)]
    nb2 = state[(i_pair[0], (i_pair[1]-1)%ly)]
    nb3 = state[((i_pair[0]+1)%lx, i_pair[1])]
    nb4 = state[((i_pair[0]-1)%lx, i_pair[1])]
    #apply condition based on neighbors: using mode
    mode_of_neighbors = st.mode([nb1, nb2, nb3, nb4, s])
    new_state.append(mode_of_neighbors)

In [5]:
new_state = np.array(new_state).reshape(lx, ly)

In [6]:
new_state

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])