In [1]:
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
import pandas as pd

In [24]:
(L-len_sequence)/3

2.0

In [26]:
#start with initial sequence: HPPHPH
len_sequence = 6 #length of sequence
L = 12 #size of matrix
init_sequence = np.array([-1,1,1,-1,1,-1])
empty_state = np.zeros((L,L))

#pad init sequence with zeros
pad_init_state = np.pad(init_sequence, (int((L-len_sequence)/2),int((L-len_sequence)/2)))
pad_init_state

array([ 0,  0,  0, -1,  1,  1, -1,  1, -1,  0,  0,  0])

In [30]:
#5 is the index which to insert, 0 is the axis.
init_state = np.insert(empty_state, int(L/2), pad_init_state, 0)  
init_state

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  1.,  1., -1.,  1., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [31]:
#choose a non-zero state:
nonzero_pos = np.where(init_state!=0)
nonzero_pos

(array([6, 6, 6, 6, 6, 6], dtype=int64),
 array([3, 4, 5, 6, 7, 8], dtype=int64))

In [32]:
#np.random.choice(nonzero_pos[0])
6

6

In [33]:
#np.random.choice(nonzero_pos[1])
6

6

In [34]:
#need to slice where nonzero elements only

sliced_ = init_state[6:6+1, 0:6]
sliced_

array([[ 0.,  0.,  0., -1.,  1.,  1.]])

In [8]:
rotated_90 = np.rot90(sliced_)
rotated_90

array([[-1.],
       [ 1.],
       [ 1.],
       [-1.]])

In [9]:
rotated_90_c = rotated_90.copy()
rotated_90_c

array([[-1.],
       [ 1.],
       [ 1.],
       [-1.]])

In [10]:
init_state[0:5+1, 0:4] = 0
init_state

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
rotated_90_c

array([[-1.],
       [ 1.],
       [ 1.],
       [-1.]])

In [14]:
#((top,bottom), (left, right))
padded_rot90 = np.pad(rotated_90_c, ((1,2), (4,1)))
padded_rot90

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
padded_rot90+init_state

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [3]:
#energy matrix: H-H = -1, others 0
def compute_energies(state):
    energy = 0
    lx, ly = state.shape
    for i_pair, s in np.ndenumerate(state):
        #get the 4 neighbors for each s
        nb1 = state[(i_pair[0], (i_pair[1]+1)%ly)]
        nb2 = state[(i_pair[0], (i_pair[1]-1)%ly)]
        nb3 = state[((i_pair[0]+1)%lx, i_pair[1])]
        nb4 = state[((i_pair[0]-1)%lx, i_pair[1])]
        
        if (nb1 == -1) and (s == -1):
            energy = energy - 1
        if (nb2 == -1) and (s == -1):
            energy = energy - 1
        if (nb3 == -1) and (s == -1):
            energy = energy - 1
        if (nb4 == -1) and (s == -1):
            energy = energy - 1
        
    return energy/2

In [4]:
compute_energies(init_state)

-1.0

In [10]:
#choose a non-zero state:
nonzero_pos = np.where(init_state!=0)
nonzero_pos

(array([5, 5, 5, 5, 5, 5], dtype=int64),
 array([0, 1, 2, 3, 4, 5], dtype=int64))

In [11]:
np.random.choice(nonzero_pos[0])

5

In [12]:
np.random.choice(nonzero_pos[1])

0

In [27]:
lx, ly = init_state.shape
for i_pair, s in np.ndenumerate(init_state):
    #get the 4 neighbors for each s
    nb1 = init_state[(i_pair[0], (i_pair[1]+1)%ly)]
    nb2 = init_state[(i_pair[0], (i_pair[1]-1)%ly)]
    nb3 = init_state[((i_pair[0]+1)%lx, i_pair[1])]
    nb4 = init_state[((i_pair[0]-1)%lx, i_pair[1])]
    
    print(i_pair, nb1, nb2, nb3, nb4)

(0, 0) 0.0 0.0 0.0 0.0
(0, 1) 0.0 0.0 0.0 0.0
(0, 2) 0.0 0.0 0.0 0.0
(0, 3) 0.0 0.0 0.0 0.0
(0, 4) 0.0 0.0 0.0 0.0
(0, 5) 0.0 0.0 0.0 0.0
(1, 0) 0.0 0.0 0.0 0.0
(1, 1) 0.0 0.0 0.0 0.0
(1, 2) 0.0 0.0 0.0 0.0
(1, 3) 0.0 0.0 0.0 0.0
(1, 4) 0.0 0.0 0.0 0.0
(1, 5) 0.0 0.0 0.0 0.0
(2, 0) 0.0 0.0 0.0 0.0
(2, 1) 0.0 0.0 0.0 0.0
(2, 2) 0.0 0.0 0.0 0.0
(2, 3) 0.0 0.0 0.0 0.0
(2, 4) 0.0 0.0 0.0 0.0
(2, 5) 0.0 0.0 0.0 0.0
(3, 0) 0.0 0.0 0.0 0.0
(3, 1) 0.0 0.0 0.0 0.0
(3, 2) 0.0 0.0 0.0 0.0
(3, 3) 0.0 0.0 0.0 0.0
(3, 4) 0.0 0.0 0.0 0.0
(3, 5) 0.0 0.0 0.0 0.0
(4, 0) 0.0 0.0 -1.0 0.0
(4, 1) 0.0 0.0 1.0 0.0
(4, 2) 0.0 0.0 1.0 0.0
(4, 3) 0.0 0.0 -1.0 0.0
(4, 4) 0.0 0.0 1.0 0.0
(4, 5) 0.0 0.0 -1.0 0.0
(5, 0) 1.0 -1.0 0.0 0.0
(5, 1) 1.0 -1.0 0.0 0.0
(5, 2) -1.0 1.0 0.0 0.0
(5, 3) 1.0 1.0 0.0 0.0
(5, 4) -1.0 -1.0 0.0 0.0
(5, 5) -1.0 1.0 0.0 0.0
(6, 0) 0.0 0.0 0.0 -1.0
(6, 1) 0.0 0.0 0.0 1.0
(6, 2) 0.0 0.0 0.0 1.0
(6, 3) 0.0 0.0 0.0 -1.0
(6, 4) 0.0 0.0 0.0 1.0
(6, 5) 0.0 0.0 0.0 -1.0


In [ ]:
def delta_energy(old_state, new_state):
    energy_old_state = compute_energies(old_state)
    energy_new_state = compute_energies(new_state)
    return energy_old_state - energy_new_state

In [ ]:
def metropolis_step(state):
    lx, ly = old_state.shape
    new_configuration = np.zeros((lx, ly))
    
    #get new_state:
    new_state = ()
    #calculate energy:
    delta_e = delta_energy(state, new_state)
    #condition: if delta_e <= 0, accept the new configuration, if not, accept the new configuration only with probability
    #p = exp(-beta*delta_e)
    if delta_e <= 0:
        new_configuration = new_state
    else:
        prob = np.exp(-beta*delta_e)
        unif = np.random.rand()
        if unif < prob:  
            new_configuration = new_state
        else:
            new_configuration = state
    return new_configuration

In [ ]:
n_realizations = 10000
beta = 10
print('orig state', state)
for i in range(n_realizations):    
    state = metropolis_step(state)
    energy_state = compute_energies(state)
    if  energy_state == -2:
        print('After', i ,'metropolis steps, the desired new_configuration having minimum energy is obtained')
        final_state = state
        break

print('final_state', final_state)